package com.hrerp.attendance.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0066CC)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDDE4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A4C)
val md_theme_light_secondary = Color(0xFF58558A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE0DDFF)
val md_theme_light_onSecondaryContainer = Color(0xFF150A45)
val md_theme_light_tertiary = Color(0xFF88658D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF1E3F5)
val md_theme_light_onTertiaryContainer = Color(0xFF2E1B30)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFEAE1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)

val md_theme_dark_primary = Color(0xFFBBD4FF)
val md_theme_dark_onPrimary = Color(0xFF003A7A)
val md_theme_dark_primaryContainer = Color(0xFF0051AC)
val md_theme_dark_onPrimaryContainer = Color(0xFFDDE4FF)
val md_theme_dark_secondary = Color(0xFFC4C0F9)
val md_theme_dark_onSecondary = Color(0xFF2E1A60)
val md_theme_dark_secondaryContainer = Color(0xFF443177)
val md_theme_dark_onSecondaryContainer = Color(0xFFE0DDFF)
val md_theme_dark_tertiary = Color(0xFFD5BCCF)
val md_theme_dark_onTertiary = Color(0xFF453047)
val md_theme_dark_tertiaryContainer = Color(0xFF5D465F)
val md_theme_dark_onTertiaryContainer = Color(0xFFF1E3F5)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE6E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C7C5)
val md_theme_dark_outline = Color(0xFF8F9297)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E6)
